### ISSUE TITLE
Error in last step

### ISSUE THREAD

**Issue by KunFang93** [jasminezhoulab/TopDom#1]
Hi, Prof. Zhou

I have run topdom smoothly until the last step and have this error message:
......
[1] "-- Done!"
[1] "-- Filtering False Positives"
[1] "-- Done!"
[1] "Step 3 Running Time : 5.09800000000018"
[1] "Step 3 : Done!"
Error in ret[i, "from.id"]:ret[i, "to.id"] : NA/NaN argument

I was wondering what might cause this problem and how could I solve it? Is this error result from no tads detected? Thanks a lot!

Kun

**Comment by KunFang93** [comment]
make coordinate start from 0 solve my problem.

**Comment by alkurowska** [comment]
It doesnt solve the problem in my case, when I make coordinate start from 0

**Comment by hanshanmengqi** [comment]
Hi @KunFang93 ,

Thanks for your informations.
Could you please tell me how to convert sparse matrix to the input matrix? As shown below:
![Picture1](https://github.com/jasminezhoulab/TopDom/assets/93769611/7c76548d-00c5-4919-918f-ed25ff0479e3)

Best,
Han
